### ISSUE TITLE
Debug=False，出现400错误

### ISSUE THREAD

**Issue by usernameisnull** [evilbinary/myblog#1]
win7 64位，把Debug=True后，就OK了
把Debug设为False，没有设置SITE_ID，why？

**Comment by evilbinary** [comment]
Debug设置为False出现什么错误？

**Comment by usernameisnull** [comment]
就没有错误了啊，就OK了。。。。。
我只是觉得好像一般的把DEBUG设为True后，还有些别的设置，好像你没有搞

**Comment by evilbinary** [comment]
额，你那边应该有些环境上得问题。
