### ISSUE TITLE
python setup.py install 这一步出错

### ISSUE THREAD

**Issue by pod4g** [evilbinary/myblog#6]
Python版本：2.7.10

OS版本：OS X EI Capitan 10.11.3

Terminal：ITerm2

![http://ww3.sinaimg.cn/large/6fd55a97jw1f2803agnanj21kw0vonap.jpg](http://ww3.sinaimg.cn/large/6fd55a97jw1f2803agnanj21kw0vonap.jpg)

**Comment by codingoc** [comment]
这是因为Mac SIP的原因，douban.fm依赖py4objc，安装时会下载最新的py4objc，系统的py4objc是2.5.1(记不太清楚)，但由于SIP，我们无法更新py4objc，所以出错了，解决办法是更新py4objc，stackoverflow上有答案

**Comment by codingoc** [comment]
我去，评论错了，手机码字，写到这个项目下去了，我也关注了这个项目，我这个评论是douban.fm的，手机上也不能删除，醉了😂

**Comment by evilbinary** [comment]
是否用了easy_install 建议使用pip 来安装，看你样子貌似是pillow出问题 ，可以暂时在setup.py去除依赖。
