### ISSUE TITLE
命令python setup.py install执行后异常，依依大神麻烦有空帮忙看下哈

### ISSUE THREAD

**Issue by Togal** [evilbinary/myblog#8]
![image](https://cloud.githubusercontent.com/assets/9533360/24082637/f94edb42-0d03-11e7-9abe-8f131d7ec414.png)

**Comment by evilbinary** [comment]
哈，python3.x的版本没测试过，你用python2.x版本。

**Comment by Togal** [comment]
用的几版本？

**Comment by Togal** [comment]
@evilbinary 用的2.7版本？

**Comment by evilbinary** [comment]
@Togal 对啊，就是2.7版本的。

**Comment by Togal** [comment]
谢谢解答！
回去试下2.7的，系统自带2.6的有问题。
